# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blu Social' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'FBSDKCoreKit'
  pod 'SwiftKeychainWrapper'
  # Pods for Blu Social

end
